-- ROWNUM : 순번을 정해 놓은 SUDO COLUMN이다.
-- 조회되는 행의 수를 제한할때 사용 
-- 11 ~ 20번까지 검색
SELECT * FROM
(SELECT ROWNUM rn, bno, title, writer, content FROM board)
WHERE rn > 10 AND rn <= 20; 


-- ROWNUM의 올바른 사용
CREATE TABLE EX_SCORE(
    NAME VARCHAR2(10),
    SCORE NUMBER
);
DROP TABLE EX_Score;
INSERT INTO EX_SCORE VALUES ('김하나', 94);
INSERT INTO EX_SCORE VALUES ('이하나', 100);
INSERT INTO EX_SCORE VALUES ('박하나', 84);
INSERT INTO EX_SCORE VALUES ('정하나', 84);
INSERT INTO EX_SCORE VALUES ('조하나', 44);
INSERT INTO EX_SCORE VALUES ('안하나', 54);
INSERT INTO EX_SCORE VALUES ('유하나', 80);
INSERT INTO EX_SCORE VALUES ('오하나', 80);
INSERT INTO EX_SCORE VALUES ('한하나', 88);
INSERT INTO EX_SCORE VALUES ('성하나', 45);

SELECT * FROM EX_SCORE;
-- 점수가 높은 순으로 5명 검색(잘못사용예)
SELECT ROWNUM , NAME, SCORE FROM EX_SCORE WHERE ROWNUM <=5 ORDER BY SCORE DESC;

-- 올바른사용 (서브쿼리 방식 - 인라인 뷰)
SELECT * FROM
(SELECT ROWNUM , NAME, SCORE FROM EX_SCORE ORDER BY SCORE DESC) WHERE ROWNUM <=5;

-- 성적 순위
SELECT name, 
 --COUNT(*) 학생수 
 RANK() OVER(ORDER BY SCORE DESC) RANK
 ,DENSE_RANK() OVER(ORDER BY SCORE DESC) DENSE_RANK
 FROM EX_SCORE;

